### PR TITLE
Added a default directory for session files

### PR DESCRIPTION
**Pull request by bobbycNH**
I added a variable "wg-default-session-dir" that is used as a default directory for "wg-open-session" and "wg-save-session-as".

### CODE REVIEW

**Comment by pashinin** [comment]
I understand what you want to do. Maybe this should be a function that gets a full path of `wg-session-file`? Because this var now has no connection with `wg-session-file`. Also `defvaralias` is not needed, I used it because I renamed an old variable to a shorter name (backwards compatibility)

Get path from current `wg-session-file` and I'll pull.

**Comment by bobbycNH** [comment]
I'm not sure what to make of the second comment there, has the build been failing right along?  It doesn't appear so, is there something wrong with the CI tool?  Did I actually break something? Is there something I can do to help clean this up?

In terms of the first, I've been a bit busy so I haven't had time to implement much but I've been rolling it around a bit.  I think your solution is to specify `(setq wg-session-file "/home/user/.emacs-sessions/default.session")` then the wg-session-dir boils down to `(defun wg-default-dir (F) (file-name-directory F))`.  This seems like it would work fine, but would it be more annoying?  I generally keep my default in `~/.emacs-default.session` and the running sessions separate.  I don't have a good justification for it, it's just the way I've done things.

As you can tell, I'm not much of an elisp hacker.  Is there a canonical way to specify default-dir and default-file?  I would expect something like "default-dir specifies where to find default-file, unless default-file includes a complete path of it's own".   I feel like this would be the most flexible method as it would allow me to say `(setq wg-default-session-dir "~/.emacs-sessions")` and `(setq wg-default-session "~/.emacs-default.session")` or `(setq wg-default-session "default.session")` (where the latter reads from "~/.emacs-sessions") and have it just do the right thing. 

Let me know what you think works best, and I'll do that!

**Comment by pashinin** [comment]
Sorry, I'm busy now, don't think u broke anything

**Comment by bobbycNH** [comment]
No worries.  Get back to me when you have some time and we'll get this merged in.  I have a temporary patch in my config so it's not holding me back.

**Comment by redguardtoo** [comment]
Users need only specify session file path or use default file path. So this PR is not needed any more.

**Pull request closed without merging**
